# lightning.pytorch==2.5.2
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: embeddings
        save_dir: /work/FAC/FBM/DBC/mrapsoma/prometex/data/logs/embeddings
        log_model: false
        tags:
          - embeddings
  callbacks:
    - class_path: ai4bmr_learn.callbacks.save_outputs.SaveOutputs
      init_args:
        step: predict
        save_dir: /users/amarti51/prometex/data/embeddings/geneformer/patch-level/${oc.env:SPLIT}
        save_key: z
        force: true
        drop_keys:
          - expression
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
data:
  class_path: ai4bmr_learn.datamodules.dataloader_collection.DataLoaderCollection
  init_args:
    dataloaders:
      predict:
        - class_path: ai4bmr_learn.datamodules.dataloader_collection.DataLoader
          init_args:
            dataset:
              class_path: ai4bmr_learn.datasets.coordinates.Coordinates
              init_args: &ds_kwargs
                coords_path: /work/PRTNR/CHUV/DIR/rgottar1/spatial/data/fmx/data/splits/hest1k-tts=4-fvs=0-min_transcripts_per_patch=200/${oc.env:SPLIT}.json
                cache_dir: /work/PRTNR/CHUV/DIR/rgottar1/spatial/data/fmx/data/cache
                metadata_path: /work/PRTNR/CHUV/DIR/rgottar1/spatial/data/fmx/data/datasets/hest1k/metadata.parquet
                index_key: global_id
                with_image: true
            collate_fn:
              class_path: ai4bmr_learn.collators.geneformer.GeneformerCollate
              init_args:
                kernel_size: 256
                stride: 256
                model_name: &MODEL_NAME gf-6L-30M-i2048
          dict_kwargs:
            batch_size: 32
            num_workers: 8
model:
  class_path: ai4bmr_learn.modules.model_builder.ModelBuilder
  init_args:
    path: ai4bmr_learn.models.encoder.geneformer.Geneformer
    batch_key: expression
    as_kwargs: true
optimizer: null
lr_scheduler: null
ckpt_path: null
