# lightning.pytorch==2.5.1.post0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    - class_path: ai4bmr_learn.logging.loggers.WandbLogger
      init_args:
        project: clf-imagenet
        save_dir: /work/FAC/FBM/DBC/mrapsoma/prometex/data/logs
        log_model: false
        tags: ['classification', 'resnet']
  callbacks:
    - class_path: ai4bmr_learn.callbacks.cache.ValidationCache
    - class_path: ai4bmr_learn.callbacks.log_model_stats.LogModelStats
    - class_path: ai4bmr_learn.callbacks.linear_probing.LinearProbing
      init_args:
        target_key: target
    - class_path: ai4bmr_learn.callbacks.linear_regression_probing.LinearRegressionProbing
      init_args:
        target_key: target
    - class_path: ai4bmr_learn.callbacks.module_checkpoint.ModuleCheckpoint
      init_args:
        module_name: backbone.backbone
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: &monitor val/f1-macro
        mode: &mode max  # "min" for loss, "max" for accuracy, etc.
        save_last: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: *monitor
        mode: *mode
        patience: 25
        min_delta: 0.001
    - class_path: ai4bmr_learn.callbacks.image_samples.ImageSamples
      init_args:
        num_samples: 5
    - class_path: ai4bmr_learn.callbacks.umap.UMAP
      init_args:
        label_key: target
        every_num_epochs: 3
  fast_dev_run: false
  max_epochs: &max_epochs 300
  min_epochs: null
  max_time: 00:01:55:00
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
data:
  class_path: ai4bmr_learn.datamodules.imagenet.ImageNet
  init_args:
    batch_size: &batch_size 64
    num_workers: 16
    persistent_workers: true
    shuffle: true
    pin_memory: true
    train_transform: &train_transform
      class_path: torchvision.transforms.v2.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: torch.float32
              scale: true
          - class_path: torchvision.transforms.v2.RandomResizedCrop
            init_args:
              size: &image_size 224
              scale: [0.8, 1]
#              ratio: [1, 1]  # TODO: crop image to largest square only
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: &mean [0.485, 0.456, 0.406]
              std: &std [0.229, 0.224, 0.225]
    val_transform:
      <<: *train_transform
model:
  backbone:
    class_path: ai4bmr_learn.models.backbones.timm.Backbone
    init_args:
      model_name: resnet18
      num_channels: 3
      global_pool: avg
      pretrained: false
  input_dim: 512
  num_classes: 10
  freeze_backbone: true
  lr: 1e-3
  weight_decay: 0.04
  pooling: flatten
optimizer: null
lr_scheduler: null
ckpt_path: null
