trainer:
  limit_train_batches: 3
  limit_val_batches: 10
  fast_dev_run: false
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: default
        save_dir: /work/FAC/FBM/DBC/mrapsoma/prometex/data/logs
        log_model: false
data:
  init_args:
    batch_size: 8
    num_workers: 0