trainer:
  fast_dev_run: false
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: maev1
        save_dir: /work/FAC/FBM/DBC/mrapsoma/prometex/data/dinov1/logs
        log_model: false
data:
  init_args:
    batch_size: 4
    num_workers: 0