model:
  class_path: sklearn.ensemble.RandomForestClassifier
  init_args:
    random_state: 4

datamodule:
  class_path: ai4bmr_learn.datamodules.PCaCellFrequencies.PCaCellFrequenciesDataModule
  init_args:
    data_path: /work/FAC/FBM/DBC/mrapsoma/prometex/data/ai4bmr-learn/PCa/data.parquet
    metadata_path: /work/FAC/FBM/DBC/mrapsoma/prometex/data/ai4bmr-learn/PCa/metadata.parquet
    target_column_name: cause_of_death

sweep:
  method: grid
  num_outer_cv: 3
  num_inner_cv: 3
  parameters:
    n_estimators:
    - 50
    - 100
    max_depth:
    - 5
    - 10
    min_samples_split:
    - 2
    - 5
    max_features:
    - sqrt
    criterion:
    - gini

wandb_init:
  project: eval_rf
  entity: chuv
  name: null
  tags: null
  notes: ''
  mode: online
  dir: /work/FAC/FBM/DBC/mrapsoma/prometex/logs/wandb


